# Generated by Django 3.2.9 on 2021-11-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.post')),
                ('author', models.CharField(default='', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('moderation', models.DateField(blank=True, default=None, null=True)),
                ('pinned', models.SmallIntegerField(default=0)),
                ('category', models.CharField(choices=[('EV', 'Event'), ('QN', 'Question'), ('GL', 'General'), ('PS', 'Pictures'), ('FS', 'For Sale')], default='GL', max_length=2)),
                ('location', models.CharField(choices=[('AI', 'Any'), ('AY', 'Alderney'), ('GY', 'Guernsey'), ('JE', 'Jersey'), ('SK', 'Sark')], default='AI', max_length=2)),
                ('subscribed_users', models.ManyToManyField(blank=True, related_name='subscribed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'permissions': [('approve_post', 'Approve Post')],
            },
            bases=('base_app.post',),
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.comment')),
                ('active', models.BooleanField(default='True')),
                ('moderation', models.DateField(blank=True, default=None, null=True)),
                ('title_slug', models.SlugField()),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='inheriting_class_app.forumpost')),
            ],
            options={
                'ordering': ['date_created'],
                'permissions': [('approve_comment', 'Approve Comment')],
            },
            bases=('base_app.comment',),
        ),
    ]
