# Generated by Django 3.2 on 2021-11-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheriting_class_app', '0002_alter_forumcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['date_created'], 'permissions': [('approve_comment', 'Approve Comment')]},
        ),
    ]
